<?php

// 用户界面语言，规则： 频道_板块_名字
return array(
		
        // 用户界面语言，规则： 频道_板块_名字
'lang_name'				   => 'zh-cn',
'guide_sellang'			   => '选择语言',
'guide_seledition'		   => '选择版本',
'typeforsearch'            => '输入搜索',
'home_webtitle'             => '扬州旅游',
'home_search'               => '搜索',
'search_empty'              => '没有找到相关记录',
//扬州概况
'yzbrief_home'             => '首&nbsp;页',
'home_briefing'            => '扬州概况',
'briefing_video'           => '扬州视频',
'yzbrief_survey'           => '扬州概况',
'yzsurvey_city'            => '城市概况',
'yzsurvey_card'            => '城市名片',
'yzsurvey_history'         => '历史文化',
'yzsurvey_culture'         => '文化丰厚',
'yzsurvey_folk'            => '民俗传统',
'yzsurvey_specialty'       => '地方特色',
'yzsurvey_develop'         => '现在发展',
'yzsurvey_blessings'       => '祝福语',
'yzbrief_feedback'         => '意见反馈',
'yzbrief_contact'          => '联系我们',
'yzbrief_news'             => '新闻动态',
'yzbrief_lineplan'         => '出行线路设计',
'line_recommend'		   =>'出行线路推荐',
'home_award'				   =>'有奖回报',
'home_jobs'                 => '人才热招',

'trpoint'                  =>'旅游指数',
'clothing'                 =>'穿衣指数',
//新闻动态
'home_news'                 => '旅游资讯',
'news_newsdetail'           => '资讯详细',
'news_newslist'             => '资讯列表',


//游客天地
'home_food'                 => '吃在扬州',
'food_spacial'              => '扬州名宴',
'food_cuisine'              => '淮扬美食',//'huaiyangmeishi<br>huaiyangmeishi',
'food_snacks'               => '特色小吃',
'food_recommend'            => '餐饮场所推荐',
'home_live'                 => '住在扬州',
'live_wineshop'             => '星级饭店',
'live_hotel'                => '商务宾馆',
'live_inn'                  => '民居客栈',
'live_official'             => '住宿场所推荐',
'home_travel'               => '行在扬州',
'travel_stat'               => '交通情况',
'travel_zhuanxian'          =>'旅游专线',
'travel_keyun'              => '长途客运',
'travel_jiaotong'           => '市内交通',
'travel_jiaotong_one'       => '途经景区公交线路',
'travel_jiaotong_two'       => '市内公交运营表',
'travel_jiaotong_three'     => '人力三轮车',
'travel_hangkong'           => '航空',
'travel_huoche'             => '火车',
'travel_zijia'              => '自驾线路',
'travel_buszulin'           => '汽车租赁',
'travel_youchuan'           => '水运',
'travel_sanlun'             => '人力三轮车',
'travel_tticket'            => '票务代理',
'home_journey'              => '游在扬州',
'journey_scenic'            => '旅游景区',
'journey_line'              => '线路推荐',
'journey_rural'             => '乡村游',
'journey_agency'            => '旅行社推荐',
'journey_strategy'          => '旅游攻略',
'journey_guester'           => '导游推荐',
'home_shopping'             => '购在扬州',
'shopping_handicraft'       => '工艺品',
'shopping_specialties'      => '地方特产',
'shopping_sites'            => '购物场所推荐',
'home_entertainment'        => '娱在扬州',
'entertainment_teahouse'    => '茶馆',
'entertainment_bath'        => '沐浴',
'entertainment_foot'        => '足艺',
'entertainment_recreation'  => '娱乐',
'entertainment_opera'       => '曲艺',
'entertainment_leisure'     => '休闲娱乐场所推荐',
'entertainment_intro'       => '简介详情',


//出行线路
'lineplan_welcome'=>'出行线路',
'lineplan_design'=>'线路设计',
'lineplan_report'=>'线路报表',
'line_person'=>'出行人数',
'line_myperson'=>'我的出行人数',
'line_days'=>'出行天数',
'line_adult'=>'成人',
'line_child'=>'儿童',
'line_destination'=>'我的出行目的',
'line_pselect'=>'请选择',
'line_begin_yztrip'=>'开始我的扬州之旅',
'line_my_triptime'=>'我的出行时间',
'line_leavedate'=>'出发日期',
'line_gobackdate'=>'返程日期',
'line_schedule_training'=>'扬州旅游行程计划',
'line_di'=>'第',
'line_tian'=>'天',
'line_hour'=>'小时',
'line_minute'=>'分钟',
'line_type'=>'行程安排',
'line_cost'=>'基本费用',
'line_totaldays'=>'预计耗时',
'line_traffic'=>'交通方式',
'line_ps'=>'备注',
'line_sel_view'=>'选择景点',
'line_sel_view_0'=>'选择景点',
'line_sel_view_1'=>'选择商店',
'line_sel_view_2'=>'选择场所',
'line_sel_view_3'=>'选择酒店',
'line_sel_view_4'=>'选择餐馆',
'line_create_report'=>'生成出行报告',
'line_am'=>'上&nbsp;&nbsp;&nbsp;&nbsp;午',
'line_launch'=>'中&nbsp;&nbsp;&nbsp;&nbsp;午',
'line_pm'=>'下&nbsp;&nbsp;&nbsp;&nbsp;午',
'line_dinner'=>'晚&nbsp;&nbsp;&nbsp;&nbsp;餐',
'line_night'=>'晚&nbsp;&nbsp;&nbsp;&nbsp;上',
'line_confirm'=>'确定',
'line_total'=>'总计',
'line_weather' =>'天气',
'line_weather1'=>'正是与家人朋友出行的好时节',
'line_weather2'=>'正是与家人朋友出行的好时节',
'line_weather3'=>'正是与家人朋友出行的好时节',
'line_weather4'=>'出门记得带伞',
'line_weather5'=>'最宜在家',
'line_waredegree'=>'穿衣指数：',
'line_tips'=>'美好的日子赶快安排一下行程吧',
'line__am' => '上午',
'line__noon' => '中午',
'line__pm' => '下午',
'line__dinner' => '晚餐',
'line__night' => '夜晚',
'line_totalcosts'=>'预计总费用',
'line_referenceonly' => '以上价格和浏览时间仅供参考',
'line_printreport'=>'打印出行报告',
'line_savereport'=>'保存出行报告',
'footy' => '步行',
'taxi' => '打的',
'bus' => '公交',
'line_money' => '元',
'line_sight'=>'旅游景点',
'line_ent'=>'娱乐场所',
'line_shop'=>'购物场所',
'line_eat'=>'餐厅',
'line_sleep'=>'住宿',
'line_tip_sight'=>'景点',
'line_tip_ent'=>'娱乐',
'line_tip_shop'=>'购物',
'line_tip_eat'=>'餐厅',
'line_tip_sleep'=>'住宿',
'line_am_tips'=>'赶快安排一下行程吧！',
'line_launch_tips'=>'淮扬美食，名不虚传！',
'line_pm_tips'=>'接下来去哪里？',
'line_dinner_tips'=>'丰盛的晚餐，可是必不可少！',
'line_night_tips'=>'扬州的夜晚，依然很美！',




'all'                       => '全部',
'author'                    => '作者',
'admin_name'                => '管理员',
'sourcefrom'                => '来源',
'datetime'                  => '时间',
'intro'                     => '简&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;介',
'aspect'                     => '看&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;点',
'f_intro'                   => '简介',
'more'                      => '更多',
'sys_name'                  => '扬州旅游局',
'copyright'                 => '版权所有',
'hotel_freetelephone'       => '酒店预定中心免费热线',
'icp_code'                  => '苏ICP备05084892号-1',
'begin_send'                => '始发',
'end_send'                  => '终发',
'train_level'               => '列车等级',
'train_no'                  => '车次',
'arrive_time'               => '抵场时间',
'leave_time'                => '离场时间',
'start_station'             => '起点站',
'end_station'               => '终点站',
'living_park'               => '途经景点',
'living_station'            => '沿途停靠',
'plan_in'                   => '进港航班信息',
'plan_out'                  => '出港航班信息',
'plan_bus'                  => '机场巴士专线',
'comp_name'                 => '单位名称',
'user_sex'                  => '性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别',
'user_female'				=> '女', 
'user_male'					=> '男',
'user_secret'				=> '保密',
'user_motto'                => '格&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;言',
'telephone'                 => '联系电话',
'address'                   => '地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址',
'dutytime'                  => '营业时间',
'opentime'                  => '开放时间',
'ticket'                    => '门票价格',
'man'                       => '成人',
'child'                     => '儿童',
'busytime'                  => '旺季',
'resettime'                 => '淡季',
'transmsg'                  => '交通信息',
'carpostmsg'                => '停车信息',
'showmoremsg'               => '查看全部',
'shownewslist'              => '查看更多',
'recom_level'               => '推荐指数',
'gotohere'                  => '到这里去',
'comment'                   => '更美的扬州，来自您真诚的评论',
'enteremail'                => '请输入您的邮箱',
'enternick'                 => '昵称',
'comment_content'           => '评论',
'nick_required'             => '昵称不可为空',
'email_type_err'            => '邮箱格式不正确',
'capt_err'                  => '请输入正确的验证码',
'title_required'            => '标题不可为空',
'con_required'              => '内容不可为空',
'entercapt'                 => '验证码',
'tips'                      => '标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;签',
'characteristicfeast'       => '特&nbsp;&nbsp;色&nbsp;&nbsp;宴',
'characteristicdish'        => '特&nbsp;&nbsp;色&nbsp;&nbsp;菜',
'classlike'                 => '相关推荐',
'comment_tips'              => '留住回忆，写写看法',
'joinnumber'                => '参与人数',
'comment_verygood'          => '满意',
'comment_well'              => '良好',
'comment_normal'            => '一般',
'comment_bad'               => '较差',
'givecomments'              => '提交评论',
'comment_success'           => '您的评论已成功提交',
'comment_err'                  => '评论失败',
'yangzhou_trans_intro'      => '扬州交通情况简介',


'name_agency'               => '旅行社',
'name_park'                 => '景点',
'name_line'                 => '线路',
'name_guester'             => '导游',
'name_spacial'              => '名宴',
'name_cuisine'              => '美食',
'name_recommend'            => '餐饮场所',
'name_leisure'              => '娱乐场所',
'name_wineshop'             => '酒店',
'name_inn'                  => '客栈',
'name_handicraft'           => '工艺品',
'name_specialties'          => '特产',
'name_sites'                => '购物场所',

'train_type'				=>'类型',
'train_leave'				=>'发车时间',
'train_arrive'				=>'到站时间',
'train_runtime'				=>'运行时间',
'train_price'				=>'参考票价',
'train_waystop'				=>'沿途停靠',

'flight_company'	=> '航空公司',
'flight_no'			=> '航班号',
'flight_type'		=> '机型',
'flight_line'		=> '航&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;线',
'flight_schedule'	=> '班&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;期',
'flight_leavetime'	=> '起飞时间',
'flight_arrivetime'	=> '到达时间',
'flight_full'		=> '全价',
'flight_fund'		=> '基金',
'flight_oil'		=> '燃油',
'home_contact'		=>'联系我们',
'home_feedback'		=>'意见反馈',
'emaile'			=> '邮箱',
'e_email'			=> '电子邮件',
'other_contact'		=>'其它联系方式',
'msg_content'		=>'留言内容',
'feedback_title'	=>'标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题',
'address_short'		=>'地址',
'zip'				=>'邮编',
'tel'				=>'电话',
'fax'				=>'传真',
'address_text'		=>'扬州市盐阜西路8号',
'map_notice'        => '注：地图位置标注仅供参考，具体情况以实际道路标实信息为准',
'hottel'            => '客服热线',
//award
'r_submit'			=>'提交反馈',
'r_redo'			=>'重新填写',

'award_weixin' => '微信',
'award_weibo' => '微博',
'award_tuniu' => '途牛网',
'award_yztrip_weibo' => '扬州旅游新浪微博官网',
'award_yztrip_tuniu' => '扬州旅游途牛网官网',
'award_other_contact' => '其它参与方式',
'award_submit_table' => '除了上述网络，如果还有其他的方式，请把网络链接地址复制到下方表格，<br/>并填写真实的姓名、联系方式等，提交后将自动传输到扬州旅游局官方邮箱！',
'award_name' => '姓名',
'award_tel' => '电话',
'award_email' => '邮件',
'award_address' => '地址',
'award_url' => '网络链接URL',
'award_subject' => '主题',
'award_rule'=> '活动规则',
'award_rule_c'=> '不论是旅游感悟，还是心情速递；不论是图文并茂，还是只言片语；不论是知名论坛，还是微博转发...... <br/>只要是您记录下的扬州旅游点滴，并将地址链接发给我们，就有机会赢得“扬州旅游季度10佳网评”。当然，还有礼品相赠哦！',
'award_remark'=> '备注',
'award_remark_c'=> '1、获奖名单将在扬州旅游网定期公布。<br/> 2、为保证您顺利收到礼品，请准确填写个人相关信息。',

'home_survey'   => '评选活动',
'survey_notice1'=> '
曾经身在扬州，是什么最让您心动不已？<br/>
对扬州心慕已久，是什么让您即刻动身？<br/>
是园林风光？还是宗教名胜？<br/>
是千年古城？还是淮扬美食？<br/>
……<br/>
现由扬州市旅游局举办的“最具吸引力的扬州旅游元素”评选活动正火热进行中，我们期待您的参与。只要您参与本次活动，我们将有一份精美的礼品（手绘扬州明信片或手绘扬州地图手绘）赠送给您。（礼品随机发送）
',
'survey_notice2'=> '活动方式：',
'survey_notice3'=> '请在主办方提供的10个扬州旅游元素中选择最吸引您的<span class="redtext">6个</span>元素（查看详细介绍请将鼠标移至图片），并将这<span class="redtext">6个</span>元素按照对您吸引力的大小进行排序。如果您的排序结果与主办方最终公布的结果一致，您将获得由主办方提供的价值1000元的扬州旅游体验券一张。',
'survey_notice4'=> '<span class="redtext">提醒：选项①-⑥代表吸引力大小程度，选项①代表最吸引您的元素。</span>',
'survey_notice5'=> '为保证您顺利收到礼品，请准确填写个人相关信息。',
'survey_A'      => '扬州园林',
'survey_B'      => '大运河',
'survey_C'      => '扬州古城',
'survey_D'      => '扬州美食',
'survey_E'      => '文化古迹',
'survey_F'      => '休闲度假',
'survey_G'      => '生态环境',
'survey_H'      => '宗教名胜',
'survey_I'      => '扬州名人',
'survey_J'      => '特色工艺',
'survey_n_A'    => '以瘦西湖、个园、何园等为代表的扬州园林历史悠久，精雅别致，其独特的风格在中国园林中占有重要地位。扬州园林集南秀北雄于一身，既有皇家园林金碧辉煌、高大瑰丽的特色，又有江南园林精巧秀丽的情调，为世人所推崇。扬州古城内散落着数量众多、风格各异的私家园林，古人曾用“园林多是宅”来形容扬州历史上城市园林之盛。',
'survey_n_B'    => '中国大运河，北起北京、南至杭州，全长2000多公里，是世界上距离最长的人工运河。扬州是“中国运河第一城”，古邗沟是中国大运河的起源。大运河扬州段是开凿最早、保存最好、遗产最多、通航最畅的一段。乘船游览扬州运河，你可以看到众多的名胜古迹、乡村古镇和田园风光。以扬州为牵头城市的大运河申遗正稳步推进，可望2014年成功。',
'survey_n_C'    => '扬州古城现存5.09平方公里，是中国保护较为完好的明清古城，也是全国重点文物保护单位。扬州古城历史遗存丰富，这里有中国十大历史文化名街东关街，还有众多的宗教寺观、私家园林、盐商老宅、名人故居、旧城遗址和民居客栈等。漫步其间，就能充分领略“唐宋元明清，从古看到今”的千年古韵。',
'survey_n_D'    => '扬州菜肴名扬天下。中国四大菜系之一的淮扬菜、闻名世界的扬州炒饭的发源地就是扬州。淮扬菜选料严谨，刀工精细、火工考究，擅于炖闷、主料突出，注重本味、咸淡适度，南北皆宜。中国的“开国第一宴”做的就是淮扬菜。此外，扬州还有令人垂涎的各式风味小吃。扬州炒饭“炒遍全球”、扬州包子“包打天下”已成为扬州城市的响亮口号。',
'survey_n_E'    => '扬州有2500年的建城史，历史上几度繁华，是国务院首批公布的24座中国历史文化名城之一。悠久灿烂的历史给这座城市留下了璀璨文化和众多古迹。这里有中国最古老的运河、汉隋炀帝的陵墓、唐宋古城的遗址、南秀北雄的园林、曲径通幽的街巷、古朴深邃的老宅。',
'survey_n_F'    => '扬州自古就是繁华、休闲的消费城市。“早上皮包水，晚上水包皮”。在这里，您可以品早茶、尝美食、泡澡堂、做足艺，体验扬州“三把刀”的高超技艺；还可以看扬剧、听评话，练习高尔夫。扬州也是“中国温泉之城”，正在建设高品质的温泉度假区。在这里，您可以尽享休闲度假、身心放松的惬意。',
'survey_n_G'    => '“绿杨城郭是扬州”。来到扬州，您会看到成片的城市绿地和滨河绿化，还有绿树成荫的街道、小区，再现了“城在林中、居在园中、路在绿中、人在景中”的意境。扬州的城郊，山青水秀，独有情趣。这里分布有众多的国家级湿地公园、全国农业旅游示范点、农业生态园和原生态的乡村田园。扬州先后获得“国家园林城市”、“国家生态示范市”等荣誉。来到扬州，您仿佛回到了大自然的怀抱。',
'survey_n_H'    => '扬州宗教资源丰富，特色鲜明，五大宗教都有遗存。佛教有唐代高僧鉴真出家的千年古刹大明寺、中国佛教禅宗的四大丛林之一的高旻寺；仙鹤寺是江苏现存最古老的伊斯兰教清真寺，也是中国东南沿海四大清真名寺之一，普哈丁园是穆罕默德十六世裔孙普哈丁的墓园；天主教有哥特式建筑风格的耶稣圣心堂；基督教有建筑独特的萃园路礼拜堂。',
'survey_n_I'    => '扬州自古开放包容、名人辈出。唐代高僧鉴真大和尚成功东渡日本，传播了中国的佛法、医药、艺术、建筑和文学。意大利旅行家马可•波罗游历中国17年，在扬州做官3年，写成《马可•波罗游记》，将扬州介绍到欧洲。新罗人崔致远在扬州求学任职五年，成为韩国汉文学的开山鼻祖。伊斯兰教先知穆罕默德第16世裔孙普哈丁来扬州传教。扬州也是前国家主席江泽民的家乡，著名诗人、文学家秦少游、汪曾琪、朱自清都是扬州人。',
'survey_n_J'    => '在中国非物质文化遗产项目中，扬州的玉雕和漆器是中国工艺美术的并蒂莲。“和田玉，扬州工”，扬州玉器玲珑剔透，北京奥运会奖牌“金镶玉”工艺在扬州完成。扬州漆器早在2000多年前，就饮誉海内，今天，清秀雅致而又丰满豪放的扬州漆器更是美不胜收。扬州剪纸线条清秀流畅，构图精巧雅致，为中国南方民间剪纸艺术的代表之一。扬州更是中国长毛绒玩具之乡。',
'survey_name'   => '姓名',
'survey_age'    => '年龄',
'survey_job'    => '职业',
'survey_addr'   => '地址',
'survey_hadcome'=> '是否来过扬州',
'survey_sheng'  => '省份',
'survey_country'=> '国家',
'survey_email'  => '邮箱',
'survey_yes'    => '是',
'survey_no'    => '否',
'survey_pselect'=>'请选择',
'age_required'  => '请选择年龄',
'job_required'  => '请填写您的职业',
'hadcom_required'=>'请选择您是否来过扬州',
'address_required'=>'请填写您的地址',
'select_required'  => '请选择6项不同的您最喜欢的元素',
'username_required'=> '请正确填写您的姓名',
'sheng_required'    => '请选择省份',
'contry_required'=>'请选择国家',
'survey_ok'      => '提交成功，感谢您的参与！',

'events_end'    =>  '本次活动已经结束，感谢您的关注！',

'achangyou'     => '扬州旅游局电子商务中心（畅游网）',

'recome_hotel'=>'推荐商家',
);