<?php

// 用户界面语言，规则： 频道_板块_名字
return array(
		
        // 用户界面语言，规则： 频道_板块_名字
'lang_name'             => 'zh-tw',

'guide_sellang'				=> '選擇語言',
'guide_seledition'				=> '選擇版本',
'typeforsearch'				=> '輸入搜索',
'home_webtitle'				=> '揚州旅遊',
'home_search'               => '搜索',
'search_empty'              => '沒有找到相關記錄',
//扬州概况
'yzbrief_home'				=> '首&nbsp;頁',
'home_briefing'            => '揚州概況',
'briefing_video'           => '揚州視頻',
'yzbrief_survey'				=> '揚州概況',
'yzsurvey_city'				=> '城市概況',
'yzsurvey_card'				=> '城市名片',
'yzsurvey_history'				=> '歷史文化',
'yzsurvey_culture'				=> '文化豐厚',
'yzsurvey_folk'				=> '民俗傳統',
'yzsurvey_specialty'				=> '地方特色',
'yzsurvey_develop'				=> '現在發展',
'yzsurvey_blessings'				=> '祝福語',
'yzbrief_feedback'				=> '意見反饋',
'yzbrief_contact'				=> '聯繫我們',
'yzbrief_news'				=> '新聞動態',
'yzbrief_lineplan'				=> '出行線路設計',
'line_recommend'				=> '出行線路推薦',
'home_award'				=> '有獎回報',
'home_jobs'                 => '人才熱招',
'trpoint'                  =>'旅遊指数',
'clothing'                 =>'穿衣指数',

//新闻动态
'home_news'				=> '旅游資訊',
'news_newsdetail'				=> '資訊詳細',
'news_newslist'				=> '資訊列表',

//游客天地
'home_food'				=> '吃在揚州',
'food_spacial'              => '揚州名宴',
'food_cuisine'				=> '淮揚美食',//'huaiyangmeishi<br>huaiyangmeishi',
'food_snacks'				=> '特色小吃',
'food_recommend'				=> '餐飲場所推薦',
'home_live'				=> '住在揚州',
'live_wineshop'				=> '星級飯店',
'live_hotel'				=> '商務賓館',
'live_inn'				=> '民居客棧',
'live_official'				=> '住宿場所推薦',
'home_travel'				=> '行在揚州',
'travel_stat'				=> '交通情況',
'travel_zhuanxian'				=> '旅遊專線',
'travel_keyun'				=> '長途客運',
'travel_jiaotong'				=> '市內交通',
'travel_jiaotong_one'				=> '途經景區公交線路',
'travel_jiaotong_two'				=> '市內公交運營表',
'travel_jiaotong_three'				=> '人力三輪車',
'travel_hangkong'				=> '航空',
'travel_huoche'				=> '火車',
'travel_zijia'				=> '自駕線路',
'travel_buszulin'				=> '汽車租賃',
'travel_youchuan'           => '水運',
'travel_sanlun'             => '人力三輪車',
'travel_tticket'            => '票務代理',
'home_journey'				=> '遊在揚州',
'journey_scenic'				=> '旅遊景區',
'journey_line'				=> '線路推薦',
'journey_rural'				=> '鄉村遊',
'journey_agency'				=> '旅行社推薦',
'journey_strategy'				=> '旅遊攻略',
'journey_guester'				=> '導遊推薦',
'home_shopping'				=> '購在揚州',
'shopping_handicraft'				=> '工藝品',
'shopping_specialties'				=> '地方特產',
'shopping_sites'				=> '購物場所推薦',
'home_entertainment'				=> '娛在揚州',
'entertainment_teahouse'				=> '茶館',
'entertainment_bath'				=> '沐浴',
'entertainment_foot'				=> '足​​藝',
'entertainment_recreation'				=> '娛樂',
'entertainment_opera'				=> '曲藝',
'entertainment_leisure'				=> '休閒娛樂場所推薦',
'entertainment_intro'				=> '簡介詳情',


//出行线路
'lineplan_welcome'				=> '出行線路',
'lineplan_design'				=> '線路設計',
'lineplan_report'				=> '線路報表',
'line_person'				=> '出行人數',
'line_myperson'				=> '我的出行人數',
'line_days'				=> '出行天數',
'line_adult'				=> '成人',
'line_child'				=> '兒童',
'line_destination'				=> '我的出行目的',
'line_pselect'				=> '請選擇',
'line_begin_yztrip'				=> '開始我的揚州之旅',
'line_my_triptime'				=> '我的出行時間',
'line_leavedate'				=> '出發日期',
'line_gobackdate'				=> '返程日期',
'line_schedule_training'				=> '揚州旅遊行程計劃',
'line_di'				=> '第',
'line_tian'				=> '天',
'line_hour'=>'小時',
'line_minute'=>'分鐘',
'line_type'				=> '行程安排',
'line_cost'				=> '基本費用',
'line_totaldays'				=> '預計耗時',
'line_traffic'				=> '交通方式',
'line_ps'=>'備註',
'line_sel_view'=>'選擇景點',
'line_sel_view_0'=>'選擇景點',
'line_sel_view_1'=>'選擇商店',
'line_sel_view_2'=>'選擇場所',
'line_sel_view_3'=>'選擇酒店',
'line_sel_view_4'=>'選擇餐館',
'line_create_report'				=> '生成出行報告',
'line_am'				=> '上&nbsp;&nbsp;&nbsp;&nbsp;午',
'line_launch'				=> '中&nbsp;&nbsp;&nbsp;&nbsp;午',
'line_pm'				=> '下&nbsp;&nbsp;&nbsp;&nbsp;午',
'line_dinner'				=> '晚&nbsp;&nbsp;&nbsp;&nbsp;餐',
'line_night'				=> '晚&nbsp;&nbsp;&nbsp;&nbsp;上',
'line_confirm'				=> '確定',
'line_total'				=> '總計',
'line_weather'				=> '天氣',
'line_weather1'				=> '正是與家人朋友出行的好時節',
'line_weather2'				=> '正是與家人朋友出行的好時節',
'line_weather3'				=> '正是與家人朋友出行的好時節',
'line_weather4'				=> '出門記得帶傘',
'line_weather5'				=> '最宜在家',
'line_waredegree'				=> '穿衣指數：',
'line_tips'				=> '美好的日子趕快安排一下行程吧',
'line__am' => '上午',
'line__noon' => '中午',
'line__pm' => '下午',
'line__dinner' => '晚餐',
'line__night' => '夜晚',
'line_totalcosts'=> '預計總費用',
'line_referenceonly' => '以上價格和瀏覽時間僅供參考',
'line_printreport' => '打印出行報告',
'line_savereport' => '保存出行報告',		
'footy'				=> '步行',
'taxi'				=> '打的',
'bus'				=> '公交',
'line_money'				=> '圆',
'line_sight'=>'旅游景点',
'line_ent'=>'娱乐场所',
'line_shop'=>'购物场所',
'line_eat'=>'餐厅',
'line_sleep'=>'住宿',
'line_tip_sight'=>'景点',
'line_tip_ent'=>'娱乐',
'line_tip_shop'=>'购物',
'line_tip_eat'=>'餐厅',
'line_tip_sleep'=>'住宿',
'line_am_tips'=>'赶快安排一下行程吧！',
'line_launch_tips'=>'淮扬美食，名不虚传！',
'line_pm_tips'=>'接下来去哪里？',
'line_dinner_tips'=>'丰盛的晚餐，可是必不可少！',
'line_night_tips'=>'扬州的夜晚，依然很美！',



'all'				=> '全部',
'author'				=> '作者',
'admin_name'				=> '管理員',
'sourcefrom'				=> '來源',
'datetime'				=> '時間',
'intro'				=> '簡&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;介',
'aspect'                     => '看&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;点',
'f_intro'				=> '簡介',
'more'				=> '更多',
'sys_name'				=> '揚州旅遊局',
'copyright'				=> '版權所有',
'hotel_freetelephone'				=> '酒店預定中心免費熱線',
'icp_code'				=> '蘇ICP備05084892號-1',
'begin_send'				=> '始發',
'end_send'				=> '終發',
'train_level'				=> '列車等級',
'train_no'				=> '車次',
'arrive_time'				=> '抵場時間',
'leave_time'				=> '離場時間',
'start_station'				=> '起點站',
'end_station'				=> '終點站',
'living_park'				=> '途經景點',
'living_station'				=> '沿途停靠',
'plan_in'				=> '進港航班信息',
'plan_out'				=> '出港航班信息',
'plan_bus'				=> '機場巴士專線',
'comp_name'				=> '單位名稱',
'user_sex'				=> '性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;別',
'user_female'				=> '女',
'user_male'				=> '男',
'user_secret'				=> '保密',
'user_motto'				=> '格&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;言',
'telephone'				=> '聯繫電話',
'address'				=> '地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址',
'dutytime'				=> '營業時間',
'opentime'				=> '開放時間',
'ticket'				=> '門票價格',
'man'				=> '成人',
'child'				=> '兒童',
'busytime'				=> '旺季',
'resettime'				=> '淡季',
'transmsg'				=> '交通信息',
'carpostmsg'				=> '停車信息',
'showmoremsg'				=> '查看全部',
'shownewslist'              => '查看更多', 
'recom_level'				=> '推薦指數',
'gotohere'				=> '到這裡去',
'comment'				=> '更美的揚州，來自您真誠的評論',
'enteremail'				=> '請輸入您的郵箱',
'enternick'				=> '暱稱',
'comment_content'           => '評論',
'nick_required'				=> '暱稱不可為空',
'email_type_err'				=> '郵箱格式不正確',
'capt_err'				=> '請輸入正確的驗證碼',
'title_required'				=> '標題不可為空',
'con_required'				=> '內容不可為空',
'entercapt'				=> '驗證碼',
'tips'				=> '標籤',
'characteristicfeast'				=> '特&nbsp;&nbsp;色&nbsp;&nbsp;宴',
'characteristicdish'				=> '特&nbsp;&nbsp;色&nbsp;&nbsp;菜',
'classlike'				=> '相關推薦',
'comment_tips'				=> '留住回憶，寫寫看法',
'joinnumber'				=> '參與人數',
'comment_verygood'				=> '滿意',
'comment_well'				=> '良好',
'comment_normal'				=> '一般',
'comment_bad'				=> '較差',
'givecomments'				=> '提交評論',
'comment_success'				=> '您的評論已成功提交',
'comment_err'				=> '評論失敗',
'yangzhou_trans_intro'				=> '揚州交通情況簡介',


'name_agency'				=> '旅行社',
'name_park'				=> '景點​​',
'name_line'				=> '線路',
'name_guester'				=> '導遊',
'name_spacial'              => '名宴',
'name_cuisine'				=> '美食',
'name_recommend'				=> '餐飲場所',
'name_leisure'				=> '娛樂場所',
'name_wineshop'				=> '酒店',
'name_inn'				=> '客棧',
'name_handicraft'				=> '工藝品',
'name_specialties'				=> '特產',
'name_sites'				=> '購物場所',

'train_type'				=> '類型',
'train_leave'				=> '發車時間',
'train_arrive'				=> '到站時間',
'train_runtime'				=> '運行時間',
'train_price'				=> '參考票價',
'train_waystop'				=> '沿途停靠',

'flight_company'				=> '航空公司',
'flight_no'				=> '航班號',
'flight_type'				=> '機型',
'flight_line'				=> '航線',
'flight_schedule'				=> '班期',
'flight_leavetime'				=> '起飛時間',
'flight_arrivetime'				=> '到達時間',
'flight_full'				=> '全價',
'flight_fund'				=> '基金',
'flight_oil'				=> '燃油',
'home_contact'				=> '聯繫我們',
'home_feedback'				=> '意見反饋',
'emaile'				=> '郵箱',
'e_email'				=> '電子郵件',
'other_contact'				=> '其它聯繫方式',
'msg_content'				=> '留言內容',
'feedback_title'				=> '標&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;題',
'address_short'				=> '地址',
'zip'				=> '郵編',
'tel'				=> '電話',
'fax'				=> '傳真',
'address_text'				=> '揚州市鹽阜西路8號',
'map_notice'        => '注：地圖位置標註僅供參考，具體情況以實際道路標實信息為準',
'hottel'            => '客服熱線',
//award
'r_submit'				=> '提交反饋',
'r_redo'				=> '重新填寫',
		
'award_weixin' => '微信',
'award_weibo' => '微博',
'award_tuniu' => '途牛網',
'award_yztrip_weibo' => '揚州旅遊新浪微博官網',
'award_yztrip_tuniu' => '揚州旅遊途牛網官網',
'award_other_contact' => '其它參與方式',
'award_submit_table' => '除了上述網絡，如果還有其他的方式，請把網絡鏈接地址複製到下方表格，<br />並填寫真實的姓名、聯繫方式等，提交後將自動傳輸到揚州旅遊局官方郵箱！ ',
'award_name' => '姓名',
'award_tel' => '電話',
'award_email' => '郵件',
'award_address' => '地址',
'award_url' => '網絡鏈接URL',
'award_subject' => '主題',
'award_rule'=> '活動規則',
'award_rule_c'=> '不論是旅遊感悟，還是心情速遞；不論是圖文並茂，還是只言片語；不論是知名論壇，還是微博轉發...... <br />只要是您記錄下的揚州旅遊點滴，並將地址鏈接發給我們，就有機會贏得“揚州旅遊季度10佳網評”。當然，還有禮品相贈哦！ ',
'award_remark'=> '備註',
'award_remark_c'=> '1、獲獎名單將在揚州旅遊網定期公佈。 <br /> 2、為保證您順利收到禮品，請準確填寫個人相關信息。 ',		

'home_survey'   => '評選活動',
'survey_notice1'=> '
曾經身在揚州，是什麼最讓您心動不已？ <br />
對揚州心慕已久，是什麼讓您即刻動身？ <br />
是園林風光？還是宗教名勝？ <br />
是千年古城？還是淮揚美食？ <br />
……<br />
現由揚州市旅遊局舉辦的“最具吸引力的揚州旅遊元素”評選活動正火熱進行中，我們期待您的參與。只要您參與本次活動，我們將有壹份精美的禮品（手繪揚州明信片或手繪揚州地圖手繪）贈送給您。（禮品隨機發送）
',
'survey_notice2'=> '活動方式：',
'survey_notice3'=> '請在主辦方提供的10個揚州旅遊元素中選擇最吸引您的<span class="redtext">6個</span>元素（查看詳細介紹請將鼠標移至圖片），並將這<span class="redtext">6個</span>元素按照對您吸引力的大小進行排序。如果您的排序結果與主辦方最終公佈的結果一致，您將獲得由主辦方提供的價值1000元的揚州旅遊體驗券一張。',
'survey_notice4'=> '<span class="redtext">提醒：選項①-⑥代表吸引力大小程度，選項①代表最吸引您的元素。</span>',
'survey_notice5'=> '為保證您順利收到禮品，請準確填寫個人相關信息。',
'survey_A' => '揚州園林',
'survey_B' => '大運河',
'survey_C' => '揚州古城',
'survey_D' => '揚州美食',
'survey_E' => '文化古蹟',
'survey_F' => '休閒度假',
'survey_G' => '生態環境',
'survey_H' => '宗教名勝',
'survey_I' => '揚州名人',
'survey_J' => '特色工藝',
'survey_n_A' => '以瘦西湖、個園、何園等為代表的揚州園林歷史悠久，精雅別緻，其獨特的風格在中國園林中佔有重要地位。揚州園林集南秀北雄於一身，既有皇家園林金碧輝煌、高大瑰麗的特色，又有江南園林精巧秀麗的情調，為世人所推崇。揚州古城內散落著數量眾多、風格各異的私家園林，古人曾用“園林多是宅”來形容揚州歷史上城市園林之盛。 ',
'survey_n_B' => '中國大運河，北起北京、南至杭州，全長2000多公里，是世界上距離最長的人工運河。揚州是“中國運河第一城”，古邗溝是中國大運河的起源。大運河揚州段是開鑿最早、保存最好、遺產最多、通航最暢的一段。乘船遊覽揚州運河，你可以看到眾多的名勝古蹟、鄉村古鎮和田園風光​​。以揚州為牽頭城市的大運河申遺正穩步推進，可望2014年成功。 ',
'survey_n_C' => '揚州古城現存5.09平方公里，是中國保護較為完好的明清古城，也是全國重點文物保護單位。揚州古城歷史遺存豐富，這裡有中國十大歷史文化名街東關街，還有眾多的宗教寺觀、私家園林、鹽商老宅、名人故居、舊城遺址和民居客棧等。漫步其間，就能充分領略“唐宋元明清，從古看到今”的千年古韻。 ',
'survey_n_D' => '揚州菜餚名揚天下。中國四大菜系之一的淮揚菜、聞名世界的揚州炒飯的發源地就是揚州。淮揚菜選料嚴謹，刀工精細、火工考究，擅於燉悶、主料突出，注重本味、鹹淡適度，南北皆宜。中國的“開國第一宴”做的就是淮揚菜。此外，揚州還有令人垂涎的各式風味小吃。揚州炒飯“炒遍全球”、揚州包子“包打天下”已成為揚州城市的響亮口號。 ',
'survey_n_E' => '揚州有2500年的建城史，歷史上幾度繁華，是國務院首批公佈的24座中國歷史文化名城之一。悠久燦爛的歷史給這座城市留下了璀璨文化和眾多古蹟。這裡有中國最古老的運河、漢隋煬帝的陵墓、唐宋古城的遺址、南秀北雄的園林、曲徑通幽的街巷、古樸深邃的老宅。 ',
'survey_n_F' => '揚州自古就是繁華、休閒的消費城市。 “早上皮包水，晚上水包皮”。在這裡，您可以品早茶、嘗美食、泡澡堂、做足藝，體驗揚州“三把刀”的高超技藝；還可以看揚劇、聽評話，練習高爾夫。揚州也是“中國溫泉之城”，正在建設高品質的溫泉度假區。在這裡，您可以盡享休閒度假、身心放鬆的愜意。 ',
'survey_n_G' => '“綠楊城郭是揚州”。來到揚州，您會看到成片的城市綠地和濱河綠化，還有綠樹成蔭的街道、小區，再現了“城在林中、居在園中、路在綠中、人在景中”的意境。揚州的城郊，山青水秀，獨有情趣。這里分布有眾多的國家級濕地公園、全國農業旅遊示範點、農業生態園和原生態的鄉村田園。揚州先後獲得“國家園林城市”、“國家生態示範市”等榮譽。來到揚州，您彷彿回到了大自然的懷抱。 ',
'survey_n_H' => '揚州宗教資源豐富，特色鮮明，五大宗教都有遺存。佛教有唐代高僧鑑真出家的千年古剎大明寺、中國佛教禪宗的四大叢林之一的高旻寺；仙鶴寺是江蘇現存最古老的伊斯蘭教清真寺，也是中國東南沿海四大清真名寺之一，普哈丁園是穆罕默德十六世裔孫普哈丁的墓園；天主教有哥特式建築風格的耶穌聖心堂；基督教有建築獨特的萃園路禮拜堂。 ',
'survey_n_I' => '揚州自古開放包容、名人輩出。唐代高僧鑑真大和尚成功東渡日本，傳播了中國的佛法、醫藥、藝術、建築和文學。意大利旅行家馬可•波羅遊歷中國17年，在揚州做官3年，寫成《馬可•波羅遊記》，將揚州介紹到歐洲。新羅人崔致遠在揚州求學任職五年，成為韓國漢文學的開山鼻祖。伊斯蘭教先知穆罕默德第16世裔孫普哈丁來揚州傳教。揚州也是前國家主席江澤民的家鄉，著名詩人、文學家秦少游、汪曾琪、朱自清都是揚州人。 ',
'survey_n_J' => '在中國非物質文化遺產項目中，揚州的玉雕和漆器是中國工藝美術的並蒂蓮。 “和田玉，揚州工”，揚州玉器玲瓏剔透，北京奧運會獎牌“金鑲玉”工藝在揚州完成。揚州漆器早在2000多年前，就飲譽海內，今天，清秀雅緻而又豐滿豪放的揚州漆器更是美不勝收。揚州剪紙線條清秀流暢，構圖精巧雅緻，為中國南方民間剪紙藝術的代表之一。揚州更是中國長毛絨玩具之鄉。 ',
'survey_name' => '姓名',
'survey_age' => '年齡',
'survey_job' => '職業',
'survey_addr' => '地址',
'survey_hadcome'=> '是否來過揚州',
'survey_sheng' => '省份',
'survey_country'=> '國家',
'survey_email' => '郵箱',
'survey_yes'    => '是',
'survey_no'    => '否',
'survey_pselect'=>'請選擇',
'age_required' => '請選擇年齡',
'job_required' => '請填寫您的職業',
'hadcom_required'=>'請選擇您是否來過揚州',
'address_required'=>'請填寫您的地址',
'select_required' => '請選擇6項不同的您最喜歡的元素',
'username_required'=> '請正確填寫您的姓名',
'sheng_required' => '請選擇省份',
'contry_required'=>'請選擇國家',
'survey_ok' => '提交成功，感謝您的參與！ ',		

'events_end'    =>  '本次活動已經結束，感謝您的關注！',

'achangyou'     => '揚州旅遊局電子商務中心（暢遊網）',

'recome_hotel'  => '推薦商家'
);